import React, { useRef, useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { X } from 'lucide-react-native';
import { commitDeliveryPartnerImportApi, DeliveryPartnerImportPreview, downloadDeliveryPartnersApi, previewDeliveryPartnerImportApi } from '../../api/deliveryPartners';
import { useAuth } from '../../contexts/AuthContext';
import { useTheme } from '../../contexts/ThemeContext';
import { AppIcon, Button, InlineAlert, Surface } from '../../ui';
import { spacing, typography } from '../../theme';

function requireWeb() { if (typeof document === 'undefined') throw new Error('Nhập và tải file hiện hỗ trợ trên giao diện Web.'); }
async function pickFile() { requireWeb(); return new Promise<{ fileName: string; fileBase64: string } | null>((resolve, reject) => { const input = document.createElement('input'); input.type = 'file'; input.accept = '.xlsx,.csv'; input.onchange = () => { const file = input.files?.[0]; if (!file) return resolve(null); if (file.size > 5 * 1024 * 1024) return reject(new Error('File tối đa 5 MB')); const reader = new FileReader(); reader.onerror = () => reject(new Error('Không thể đọc file')); reader.onload = () => resolve({ fileName: file.name, fileBase64: String(reader.result).split(',')[1] }); reader.readAsDataURL(file); }; input.click(); }); }
function save(blob: Blob, fileName: string) { requireWeb(); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = fileName; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); }

export function DeliveryPartnerImportModal({ visible, onClose, onImported }: { visible: boolean; onClose: () => void; onImported: (count: number) => void }) {
  const { token } = useAuth(); const { theme } = useTheme(); const [preview, setPreview] = useState<DeliveryPartnerImportPreview | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const busyRef = useRef(false);
  const run = async (action: () => Promise<void>) => { if (busyRef.current) return; busyRef.current = true; setBusy(true); setError(''); try { await action(); } catch (failure: any) { setError(failure.message || 'Không thể xử lý file'); } finally { busyRef.current = false; setBusy(false); } };
  const choose = () => run(async () => { const file = await pickFile(); if (file) { setPreview(null); setPreview(await previewDeliveryPartnerImportApi(token, file.fileName, file.fileBase64)); } });
  const template = () => run(async () => save(await downloadDeliveryPartnersApi(token, {}, 'xlsx', true), 'Mau_doi_tac_giao_hang.xlsx'));
  const commit = () => run(async () => { if (!preview || preview.errorRows.length || !preview.validRows.length) return; const result = await commitDeliveryPartnerImportApi(token, preview.validRows.map(row => row.data)); onImported(result.createdCount); });
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.backdrop}><Surface level="raised" style={styles.modal}><View style={[styles.header, { borderBottomColor: theme.borderSubtle }]}><Text style={[styles.title, { color: theme.textPrimary }]}>Nhập đối tác giao hàng</Text><Pressable onPress={onClose}><AppIcon icon={X} color={theme.textPrimary} /></Pressable></View><ScrollView contentContainerStyle={styles.content}><Text style={[styles.copy, { color: theme.textSecondary }]}>Nhập mới tối đa 500 dòng XLSX hoặc CSV (5 MB). Mã trùng không được ghi đè; có lỗi thì không dòng nào được nhập.</Text><View style={styles.actions}><Button variant="secondary" label="Tải file mẫu" disabled={busy} onPress={template} /><Button variant="primary" label="Chọn file" disabled={busy} onPress={choose} /></View>{!!error && <InlineAlert message={error} />}{preview && <><Text style={[styles.copy, { color: theme.textPrimary }]}>{preview.fileName} — {preview.validRows.length} hợp lệ, {preview.errorRows.length} lỗi</Text>{preview.errorRows.map(row => <InlineAlert key={row.rowNumber} message={`Dòng ${row.rowNumber} · ${row.name}: ${row.error}`} />)}</>}</ScrollView><View style={[styles.footer, { borderTopColor: theme.borderSubtle }]}><Button variant="quiet" label="Đóng" disabled={busy} onPress={onClose} /><Button variant="primary" label={`Nhập ${preview?.validRows.length || 0} đối tác`} loading={busy} disabled={!preview?.validRows.length || !!preview.errorRows.length} onPress={commit} /></View></Surface></View></Modal>;
}
const styles = StyleSheet.create({ backdrop: { alignItems: 'center', backgroundColor: 'rgba(15,23,42,0.45)', flex: 1, justifyContent: 'center', padding: spacing.lg }, modal: { maxHeight: '86%', maxWidth: 680, width: '100%' }, header: { alignItems: 'center', borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', padding: spacing.lg }, title: { fontFamily: typography.families.operationalBold, fontSize: typography.sizes.xl }, content: { gap: spacing.md, padding: spacing.lg }, copy: { fontFamily: typography.families.body, fontSize: typography.sizes.sm, lineHeight: 20 }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, footer: { borderTopWidth: 1, flexDirection: 'row', gap: spacing.sm, justifyContent: 'flex-end', padding: spacing.md } });
