import React, { useRef, useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { FileSpreadsheet, Upload, X } from 'lucide-react-native';
import { commitTableImportApi, downloadTablesApi, previewTableImportApi, TableImportPreview } from '../../api/tableManagement';
import { useAuth } from '../../contexts/AuthContext';
import { useTheme } from '../../contexts/ThemeContext';
import { radii, spacing, typography } from '../../theme';
import { AppIcon, Button, InlineAlert, Surface } from '../../ui';
import { pickTableFile, saveTableFile } from './tableFiles';

export function TableImportModal({ visible, onClose, onImported }: { visible: boolean; onClose: () => void; onImported: (count: number) => void }) {
  const { token } = useAuth(); const { theme } = useTheme(); const [preview, setPreview] = useState<TableImportPreview | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const busyRef = useRef(false);
  const run = async (action: () => Promise<void>) => { if (busyRef.current) return; busyRef.current = true; setBusy(true); setError(''); try { await action(); } catch (failure: any) { setError(failure.message || 'Không thể xử lý file'); } finally { busyRef.current = false; setBusy(false); } };
  const choose = () => void run(async () => { const file = await pickTableFile(); if (file) setPreview(await previewTableImportApi(token, file.fileName, file.fileBase64)); });
  const template = () => void run(async () => { await saveTableFile(await downloadTablesApi(token, {}, 'xlsx', true), 'Mau_phong_ban.xlsx'); });
  const commit = () => void run(async () => { if (!preview || preview.errorRows.length || !preview.validRows.length) return; const result = await commitTableImportApi(token, preview.validRows.map(row => row.data)); onImported(result.createdCount); setPreview(null); });
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.backdrop}><Surface level="raised" style={styles.modal}><View style={[styles.header, { borderBottomColor: theme.borderSubtle }]}><View><Text style={[styles.title, { color: theme.textPrimary }]}>Nhập danh sách phòng/bàn</Text><Text style={[styles.copy, { color: theme.textSecondary }]}>XLSX hoặc CSV · tối đa 500 dòng, 5 MB</Text></View><Pressable accessibilityLabel="Đóng" onPress={onClose}><AppIcon icon={X} color={theme.textPrimary} /></Pressable></View><ScrollView contentContainerStyle={styles.content}><Text style={[styles.copy, { color: theme.textSecondary }]}>Khu vực phải được tạo trước. Hệ thống chỉ ghi dữ liệu khi toàn bộ các dòng đều hợp lệ.</Text><View style={styles.actions}><Button variant="secondary" label="Tải file mẫu" icon={FileSpreadsheet} disabled={busy} onPress={template} /><Button variant="primary" label="Chọn file" icon={Upload} disabled={busy} onPress={choose} /></View>{!!error && <InlineAlert message={error} />}{preview && <Surface level="sunken" style={styles.preview}><Text style={[styles.previewTitle, { color: theme.textPrimary }]}>{preview.fileName}</Text><Text style={[styles.copy, { color: theme.textSecondary }]}>{preview.validRows.length} dòng hợp lệ · {preview.errorRows.length} dòng lỗi</Text>{preview.errorRows.map(row => <InlineAlert key={row.rowNumber} message={`Dòng ${row.rowNumber} · ${row.name || 'Chưa có tên'}: ${row.error}`} />)}</Surface>}</ScrollView><View style={[styles.footer, { borderTopColor: theme.borderSubtle }]}><Button variant="quiet" label="Bỏ qua" disabled={busy} onPress={onClose} /><Button variant="primary" label={`Nhập ${preview?.validRows.length || 0} phòng/bàn`} loading={busy} disabled={!preview?.validRows.length || !!preview.errorRows.length} onPress={commit} /></View></Surface></View></Modal>;
}
const styles = StyleSheet.create({ backdrop: { alignItems: 'center', backgroundColor: 'rgba(15,23,42,0.48)', flex: 1, justifyContent: 'center', padding: spacing.lg }, modal: { maxHeight: '88%', maxWidth: 720, width: '100%' }, header: { alignItems: 'center', borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', padding: spacing.lg }, title: { fontFamily: typography.families.operationalBold, fontSize: typography.sizes.xl }, copy: { fontFamily: typography.families.body, fontSize: typography.sizes.sm, lineHeight: 20 }, content: { gap: spacing.lg, padding: spacing.lg }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, preview: { borderRadius: radii.md, gap: spacing.sm, padding: spacing.md }, previewTitle: { fontFamily: typography.families.bodySemibold, fontSize: typography.sizes.md }, footer: { borderTopWidth: 1, flexDirection: 'row', gap: spacing.sm, justifyContent: 'flex-end', padding: spacing.md } });
