import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions } from 'react-native';
import { Check, Download, FileSpreadsheet, Plus, RefreshCw, RotateCcw, Search } from 'lucide-react-native';
import { useAuth } from '../../contexts/AuthContext';
import { useRestaurant } from '../../contexts/RestaurantContext';
import { useTheme } from '../../contexts/ThemeContext';
import { downloadPurchaseReturnExportApi, fetchPurchaseReturnsApi } from '../../api/purchaseReturns';
import type { PurchaseReturnDto, PurchaseReturnListFilter, PurchaseReturnStatus } from '../../api/contracts';
import { radii, spacing, typography } from '../../theme';
import { AppIcon, Button, EmptyState, InlineAlert, ScreenHeader, StatusBadge, Surface } from '../../ui';
import { formatPurchaseReturnMoney, getPurchaseReturnStatusPresentation } from './purchaseReturnViewModel';

export interface PurchaseReturnListScreenProps { onCreateReturn: () => void; onOpenReturn: (id: number) => void }
const statuses: Array<{ value: PurchaseReturnStatus; label: string }> = [{ value: 'DRAFT', label: 'Phiếu tạm' }, { value: 'COMPLETED', label: 'Đã hoàn thành' }, { value: 'CANCELLED', label: 'Đã hủy' }];
const initialFilter: PurchaseReturnListFilter = { statuses: ['DRAFT', 'COMPLETED'], page: 1, pageSize: 50 };
function date(value: string): string { return new Date(value).toLocaleString('vi-VN', { dateStyle: 'short', timeStyle: 'short' }); }
function triggerDownload(blob: Blob, fileName: string): boolean { if (Platform.OS !== 'web' || typeof window === 'undefined' || typeof document === 'undefined') return false; const url = window.URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = fileName; document.body.appendChild(anchor); anchor.click(); document.body.removeChild(anchor); window.URL.revokeObjectURL(url); return true; }

function ReturnRow({ item, onPress }: { item: PurchaseReturnDto; onPress: () => void }) {
  const { theme } = useTheme();
  const status = getPurchaseReturnStatusPresentation(item.status);
  return <Pressable onPress={onPress} style={({ pressed }) => [styles.row, { borderBottomColor: theme.borderSubtle, backgroundColor: pressed ? theme.interactiveQuiet : theme.surfaceBase }]}>
    <Text style={[styles.code, { color: theme.primary }]}>{item.returnCode}</Text>
    <Text style={[styles.date, { color: theme.textPrimary }]}>{date(item.returnedAt)}</Text>
    <Text style={[styles.supplier, { color: theme.textPrimary }]} numberOfLines={1}>{item.supplier?.name || '—'}</Text>
    <Text style={[styles.money, { color: theme.textPrimary }]}>{formatPurchaseReturnMoney(item.subtotalAmount)}</Text>
    <Text style={[styles.money, { color: theme.primary }]}>{formatPurchaseReturnMoney(item.payableAmount)}</Text>
    <Text style={[styles.money, { color: theme.textSecondary }]}>{formatPurchaseReturnMoney(item.refundAmount)}</Text>
    <View style={styles.status}><StatusBadge tone={status.tone} label={status.label} /></View>
  </Pressable>;
}
export const PurchaseReturnListScreen: React.FC<PurchaseReturnListScreenProps> = ({ onCreateReturn, onOpenReturn }) => {
  const { theme } = useTheme();
  const { token } = useAuth();
  const { inventoryRevision } = useRestaurant();
  const { width } = useWindowDimensions();
  const [filter, setFilter] = useState(initialFilter); const [search, setSearch] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState('');
  const [data, setData] = useState<Awaited<ReturnType<typeof fetchPurchaseReturnsApi>> | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [exporting, setExporting] = useState<'csv' | 'xlsx' | null>(null);
  const currentFilter = useMemo(() => ({ ...filter, search, from: from || undefined, to: to || undefined }), [filter, from, search, to]);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setData(await fetchPurchaseReturnsApi(token, currentFilter)); } catch (e: any) { setError(e.message || 'Không thể tải phiếu trả hàng nhập'); } finally { setLoading(false); } }, [currentFilter, token]);
  useEffect(() => { void load(); }, [load, inventoryRevision]);
  const toggle = (status: PurchaseReturnStatus) => setFilter(current => ({ ...current, page: 1, statuses: (current.statuses || []).includes(status) ? (current.statuses || []).filter(item => item !== status) : [...(current.statuses || []), status] }));
  const exportFile = async (format: 'csv' | 'xlsx') => { setExporting(format); try { const blob = await downloadPurchaseReturnExportApi(token, currentFilter, format); if (!triggerDownload(blob, 'Phieu_tra_hang_nhap_' + new Date().toISOString().slice(0, 10) + '.' + format)) setError('File đã được tạo. Tải file hiện hỗ trợ trên giao diện Web.'); } catch (e: any) { setError(e.message || 'Không thể xuất phiếu trả hàng nhập'); } finally { setExporting(null); } };
  const narrow = width < 900;
  return <ScrollView style={[styles.screen, { backgroundColor: theme.surfaceCanvas }]} contentContainerStyle={styles.content}>
    <ScreenHeader title="Phiếu trả hàng nhập" description="Theo dõi hàng trả nhà cung cấp; tồn kho chỉ giảm khi hoàn thành." leading={<View style={[styles.mark, { backgroundColor: theme.interactiveSecondary }]}><AppIcon icon={RotateCcw} color={theme.primary} /></View>} actions={<View style={styles.headerActions}><Button variant="secondary" label="CSV" icon={Download} loading={exporting === 'csv'} onPress={() => void exportFile('csv')} /><Button variant="secondary" label="XLSX" icon={FileSpreadsheet} loading={exporting === 'xlsx'} onPress={() => void exportFile('xlsx')} /><Button variant="primary" label="Trả hàng nhập" icon={Plus} onPress={onCreateReturn} /></View>} />
    {error && <InlineAlert title="Không thể tải dữ liệu" message={error} tone="danger" />}
    <View style={[styles.layout, narrow && styles.narrow]}>
      <Surface level="base" style={[styles.filters, narrow && styles.filtersNarrow, { borderColor: theme.borderSubtle }]}>
        <View style={styles.filterHeading}><AppIcon icon={Check} color={theme.textSecondary} size={16} /><Text style={[styles.panelTitle, { color: theme.textPrimary }]}>Bộ lọc</Text></View>
        <Text style={[styles.label, { color: theme.textSecondary }]}>Thời gian</Text><View style={styles.dateRow}><TextInput value={from} onChangeText={setFrom} placeholder="Từ ngày" placeholderTextColor={theme.textSecondary} style={[styles.dateInput, { borderColor: theme.borderSubtle, color: theme.textPrimary }]} /><TextInput value={to} onChangeText={setTo} placeholder="Đến ngày" placeholderTextColor={theme.textSecondary} style={[styles.dateInput, { borderColor: theme.borderSubtle, color: theme.textPrimary }]} /></View>
        <Text style={[styles.label, { color: theme.textSecondary }]}>Trạng thái</Text>{statuses.map(option => { const active = filter.statuses?.includes(option.value) ?? false; return <Pressable key={option.value} onPress={() => toggle(option.value)} style={styles.choice}><View style={[styles.checkbox, { borderColor: active ? theme.primary : theme.borderSubtle, backgroundColor: active ? theme.primary : theme.surfaceBase }]}>{active && <AppIcon icon={Check} color="#fff" size={14} />}</View><Text style={{ color: theme.textPrimary }}>{option.label}</Text></Pressable>; })}
      </Surface>
      <Surface level="raised" style={styles.tableSurface}>
        <View style={styles.toolbar}><View style={[styles.search, { borderColor: theme.borderSubtle, backgroundColor: theme.surfaceBase }]}><AppIcon icon={Search} color={theme.textSecondary} size={18} /><TextInput value={search} onChangeText={setSearch} placeholder="Mã trả hàng" placeholderTextColor={theme.textSecondary} style={[styles.searchInput, { color: theme.textPrimary }]} /></View><Button variant="quiet" label="Làm mới" icon={RefreshCw} loading={loading} onPress={load} /></View>
        {loading && !data ? <View style={styles.state}><ActivityIndicator color={theme.primary} /><Text style={{ color: theme.textSecondary }}>Đang tải...</Text></View> : data && data.items.length === 0 ? <EmptyState title="Chưa có phiếu trả hàng nhập" description="Nhấn Trả hàng nhập để tạo phiếu mới." action={<Button variant="primary" label="Trả hàng nhập" icon={Plus} onPress={onCreateReturn} />} /> : data ? <ScrollView horizontal><View style={styles.table}><View style={[styles.header, { backgroundColor: theme.interactiveSecondary, borderBottomColor: theme.primary }]}>{['Mã trả hàng', 'Thời gian', 'Nhà cung cấp', 'Tổng hàng', 'Phải trả', 'Đã hoàn', 'Trạng thái'].map((label, index) => <Text key={label} style={[index === 0 ? styles.code : index === 1 ? styles.date : index === 2 ? styles.supplier : index === 6 ? styles.status : styles.money, styles.headerText, { color: theme.textPrimary }]}>{label}</Text>)}</View>{data.items.map(item => <ReturnRow key={item.id} item={item} onPress={() => onOpenReturn(item.id)} />)}<View style={[styles.pagination, { borderTopColor: theme.borderSubtle }]}><Text style={{ color: theme.textSecondary }}>Trang {data.pagination.page}/{Math.max(data.pagination.totalPages, 1)} · {data.pagination.totalRows} phiếu</Text><View style={styles.pageButtons}><Button variant="quiet" label="Trước" disabled={data.pagination.page <= 1} onPress={() => setFilter(current => ({ ...current, page: current.page! - 1 }))} /><Button variant="quiet" label="Sau" disabled={data.pagination.page >= data.pagination.totalPages} onPress={() => setFilter(current => ({ ...current, page: current.page! + 1 }))} /></View></View></View></ScrollView> : null}
        {data && data.items.length > 0 && <View style={[styles.summary, { borderTopColor: theme.borderSubtle }]}><Text style={{ color: theme.textSecondary }}>Tổng phải trả</Text><Text style={[styles.summaryValue, { color: theme.primary }]}>{formatPurchaseReturnMoney(data.summary.totalDue)}</Text></View>}
      </Surface>
    </View>
  </ScrollView>;
};
const styles = StyleSheet.create({ screen: { flex: 1 }, content: { gap: spacing.lg, padding: spacing.lg }, mark: { alignItems: 'center', borderRadius: radii.md, height: 44, justifyContent: 'center', width: 44 }, headerActions: { flexDirection: 'row', gap: spacing.sm }, layout: { flexDirection: 'row', gap: spacing.lg }, narrow: { flexDirection: 'column' }, filters: { borderRadius: radii.md, borderWidth: 1, gap: spacing.md, padding: spacing.md, width: 250 }, filtersNarrow: { width: '100%' }, filterHeading: { alignItems: 'center', flexDirection: 'row', gap: spacing.xs }, panelTitle: { fontFamily: typography.families.bodySemibold, fontSize: typography.sizes.md }, label: { fontFamily: typography.families.bodySemibold, marginTop: spacing.xs }, dateRow: { flexDirection: 'row', gap: spacing.xs }, dateInput: { borderRadius: radii.sm, borderWidth: 1, flex: 1, minHeight: 40, paddingHorizontal: spacing.sm }, choice: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, minHeight: 34 }, checkbox: { alignItems: 'center', borderRadius: 4, borderWidth: 1, height: 19, justifyContent: 'center', width: 19 }, tableSurface: { flex: 1, minWidth: 0, overflow: 'hidden' }, toolbar: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, justifyContent: 'space-between', padding: spacing.md }, search: { alignItems: 'center', borderRadius: radii.md, borderWidth: 1, flex: 1, flexDirection: 'row', gap: spacing.sm, maxWidth: 520, minHeight: 44, paddingHorizontal: spacing.md }, searchInput: { flex: 1, minHeight: 40 }, state: { alignItems: 'center', gap: spacing.md, justifyContent: 'center', minHeight: 360 }, table: { minWidth: 1120 }, header: { borderBottomWidth: 1, flexDirection: 'row', minHeight: 44, padding: spacing.md }, headerText: { fontFamily: typography.families.bodySemibold, fontSize: typography.sizes.xs }, row: { alignItems: 'center', borderBottomWidth: 1, flexDirection: 'row', minHeight: 58, paddingHorizontal: spacing.md, paddingVertical: spacing.sm }, code: { width: 145 }, date: { width: 155 }, supplier: { width: 240 }, money: { textAlign: 'right', width: 145 }, status: { alignItems: 'flex-start', width: 150 }, pagination: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', padding: spacing.md }, pageButtons: { flexDirection: 'row', gap: spacing.sm }, summary: { alignItems: 'center', borderTopWidth: 1, flexDirection: 'row', gap: spacing.sm, justifyContent: 'flex-end', padding: spacing.md }, summaryValue: { fontFamily: typography.families.operationalBold, fontSize: typography.sizes.md } });
