CREATE TABLE IF NOT EXISTS SupplierGroup (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL,
  UNIQUE INDEX SupplierGroup_name_key(name),
  PRIMARY KEY (id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE Supplier
  ADD COLUMN identityNumber VARCHAR(20) NULL,
  ADD COLUMN province VARCHAR(100) NULL,
  ADD COLUMN district VARCHAR(100) NULL,
  ADD COLUMN ward VARCHAR(100) NULL,
  ADD COLUMN companyName VARCHAR(200) NULL,
  ADD COLUMN groupId INTEGER NULL;
CREATE INDEX Supplier_groupId_idx ON Supplier(groupId);
ALTER TABLE Supplier ADD CONSTRAINT Supplier_groupId_fkey FOREIGN KEY (groupId) REFERENCES SupplierGroup(id) ON DELETE RESTRICT ON UPDATE CASCADE;
