-- AlterTable
ALTER TABLE `Order` MODIFY COLUMN `paymentStatus` ENUM('UNPAID', 'PAID', 'VOIDED') NOT NULL DEFAULT 'UNPAID';

-- AlterTable
ALTER TABLE `DiningTable` MODIFY COLUMN `status` ENUM('AVAILABLE', 'OCCUPIED', 'DIRTY', 'NEED_CLEANING') NOT NULL DEFAULT 'AVAILABLE';
